version: '3.8'

services:
  web:
    container_name: order_api
    build: .
    command: alembic revision --autogenerate -m "init" && alembic upgrade head && python main.py
    volumes:
      - .:/app/volumes_data
    ports:
      - 8080:8080
    networks:
      - order-network
    depends_on:
      - db
    restart: always
  
  db:
    image: postgres:13-alpine
    container_name: postgre_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1905
      - POSTGRES_DB=test_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - order-network
    restart: always

volumes:
  postgres_data:

networks:
  order-network: