version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0:8000 --reload
    volumes:
      - .:/app/volumes_data
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL
      - HASH_CODE
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=fastapi_order_db

volumes:
  postgres_data: