"""init

Revision ID: 00d3c5c7e64b
Revises: 85edc5ed9b04
Create Date: 2022-12-29 15:56:26.186180

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision = '00d3c5c7e64b'
down_revision = '85edc5ed9b04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
