"""init

Revision ID: 5a63a5063e1c
Revises: f8697fca3b6e
Create Date: 2022-12-27 16:05:01.583084

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision = '5a63a5063e1c'
down_revision = 'f8697fca3b6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
