"""init

Revision ID: 85edc5ed9b04
Revises: fa9130136eb0
Create Date: 2022-12-29 15:36:16.652769

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision = '85edc5ed9b04'
down_revision = 'fa9130136eb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
