"""init

Revision ID: a593bb8fc1e9
Revises: 00d3c5c7e64b
Create Date: 2023-01-04 14:47:02.614415

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision = 'a593bb8fc1e9'
down_revision = '00d3c5c7e64b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
