"""init

Revision ID: ea266122d5ba
Revises: 6f6830693af1
Create Date: 2022-12-27 16:39:22.233791

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea266122d5ba'
down_revision = '6f6830693af1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False))
    op.add_column('users', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False))
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_users_age', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('users_modified_by_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_created_by_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'modified_on')
    op.drop_column('users', 'modified_by')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('modified_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('modified_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_created_by_fkey', 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key('users_modified_by_fkey', 'users', 'users', ['modified_by'], ['id'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_age', 'users', ['age'], unique=False)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
